### ISSUE TITLE
iqtree2 taking a long time to run

### ISSUE THREAD

**Issue by elserj** [gp201/Freyja_pathogen_workflow_v2#4]
I am trying to run this but it has been running for over a week on the iqtree step. Is there a way to speed that up? It is running on a 64 core machine, but I see that iqtree decided that 2 cores was optimal.

Any other thoughts on ways to speed it up?

**Comment by gp201** [comment]
@elserj Thanks for bringing this up.

How many sequences are you using to construct the tree?

One way to speed things up is by adjusting the nucleotide model from ModelFinder to a specific nucleotide model fits the pathogen you're working with. You can make that change here: https://github.com/gp201/Freyja_pathogen_workflow_v2/blob/b6113d2e5ce00aa5355ffed7dccfe8e9b791e22d/nextflow.config#L44

If it's still running too slowly, another option is to generate the tree (newick format) separately and provide it to the workflow, which will let you bypass the iqtree step entirely: https://github.com/gp201/Freyja_pathogen_workflow_v2/blob/b6113d2e5ce00aa5355ffed7dccfe8e9b791e22d/nextflow.config#L36

**Comment by elserj** [comment]
Thanks for the info.

I am running it with ~28k sequences.

Does it matter much which nucleotide model to use? Which one do you use for your runs? I'm running this for RSV for now but would like to run it for other viruses in the future.

**Comment by gp201** [comment]
@elserj I haven’t personally worked with 28K sequences before. However, I recommend trying to downsample the sequences. If you want to use all of them, you can check out this guide: https://github.com/roblanf/sarscov2phylo/blob/master/tree_estimation.md#whats-the-best-method-to-get-a-tree-of-10k-sars-cov-2-sequences for tips on speeding up the process with large datasets.

For reference, we pull data from https://nextstrain.org/rsv/a/genome/6y, which contains around 3K sequences so it's much faster.

**Comment by elserj** [comment]
Thank you for the help. I got busy and didn't get back to this till now, but I ran in to another issue I wanted to ask about. Feel free to split off to another issue if you want.

I downsampled the 28K sequences down to 1000, and changed the "iqtree_nucleotide_model" to "GTR+F" and it then only takes a few hours to finish the IQtree step.

However, the pipeline then crashes with the following error:
```
Caused by:
  Process `FORMAT_CLADES_TSV` terminated with an error exit status (1)


Command executed:

  clades_tsv_formatter.py -m 2_auspice_metadata.tsv -s "name" -l "lineage" -o formatted_clades.tsv

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/home/bpp/elserj/.nextflow/assets/gp201/Freyja_pathogen_workflow_v2/bin/clades_tsv_formatter.py", line 60, in <module>
      main()
    File "/home/bpp/elserj/.nextflow/assets/gp201/Freyja_pathogen_workflow_v2/bin/clades_tsv_formatter.py", line 52, in main
      df = switch_columns(df[[args.strain_col, args.lineage_col]].copy(
                          ~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/nfs7/external/TRACE/elserj/RSV/freyja_barcodes/work/conda/clades_tsv_formatter-53dc3de3ebe546539e7a9e3124448af2/lib/python3.11/site-packages/pandas/core/frame.py", line 3767, in __getitem__
      indexer = self.columns._get_indexer_strict(key, "columns")[1]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/nfs7/external/TRACE/elserj/RSV/freyja_barcodes/work/conda/clades_tsv_formatter-53dc3de3ebe546539e7a9e3124448af2/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 5877, in _get_indexer_strict
      self._raise_if_missing(keyarr, indexer, axis_name)
    File "/nfs7/external/TRACE/elserj/RSV/freyja_barcodes/work/conda/clades_tsv_formatter-53dc3de3ebe546539e7a9e3124448af2/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 5941, in _raise_if_missing
      raise KeyError(f"{not_found} not in index")
  KeyError: "['lineage'] not in index"
```

I tried digging in to it a bit on my own, and figured out that it is being caused by the `nextflow.config` option `lineage_column` being set to `lineage`, and the `metadata.tsv` file not having that in the file. However, even changing it to `clade` that is in the metadata.tsv file didn't work either, with the same error (`KeyError: "['clade'] not in index"`).

I managed to get it to complete by checking out the `2_auspice_metadata.tsv` manually, and changing the "
`lineage_column` to `'GRI Lineage Level 7'`

So, is that the correct setting for that parameter? Is there another way I should deduce what it should be?

**Comment by gp201** [comment]
@elserj I apologize for the delayed response. This is an intriguing issue and definitely shouldn't be occurring. Could you please share the files that would allow me to reproduce the error and resolve it?

**Comment by elserj** [comment]
Sure, I just used the files from nextstrain.org. They may have updated since I downloaded them on Aug 2, but I just downloaded them with
```
wget https://data.nextstrain.org/files/workflows/rsv/a/metadata.tsv.gz
wget https://data.nextstrain.org/files/workflows/rsv/a/sequences.fasta.xz
```

and the nextstrain.json from https://nextstrain.org/rsv/a/genome/6y by clicking on the "Download Data" pop-up at the bottom and the clicking "AUSPICE (NEXTSTRAIN) JSON" link.

I should point out, that even though I did get it to run, the lineage data was still wrong when I took a look at the barcode.csv file in detail. I see the following:
```
[elserj@shell-hpc GENERATE_BARCODES]$ cat barcode.csv | awk -F ',' '{print $1}' | sort | uniq
A
A.0
A.0.0
A.0.0.0.1
A.0.0.0.2
A.0.0.1
A.0.0.10
A.0.0.11
A.0.0.31
A.0.0.4.1
....
```

which I would expect it to look like what you have at https://github.com/andersen-lab/Freyja-barcodes/blob/main/RSVa/2024-03-15/barcode.csv, and it does not match.

**Comment by gp201** [comment]
I apologize for the delayed response. This issue may be caused by the `skip_clade_assignment` parameter being set to `false`. If you change it to `true`, you shouldn't see this error occur.
